global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-gateway:3000
  - job_name: worker
    static_configs:
      - targets:
          - worker:9100
  - job_name: tax-engine
    metrics_path: /metrics
    static_configs:
      - targets:
          - tax-engine:8000
