// Auto-generated by scripts/gen-front-contracts.ts. Do not edit.

import { z } from "zod";

export const AllocationPreviewV = z.any();

export const AuditV = z.any();

export const GateV = z.any();

export const LedgerEntryV = z.any();

export const PolicyV = z.any();

export const RptV = z.any();

