// Auto-generated by scripts/gen-front-contracts.ts. Do not edit.

import { z } from "zod";
import { AllocationPreviewV, AuditV, GateV, LedgerEntryV, PolicyV, RptV } from "./schemas";

export type AllocationPreview = z.infer<typeof AllocationPreviewV>;
export type Audit = z.infer<typeof AuditV>;
export type Gate = z.infer<typeof GateV>;
export type LedgerEntry = z.infer<typeof LedgerEntryV>;
export type Policy = z.infer<typeof PolicyV>;
export type Rpt = z.infer<typeof RptV>;
