name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm -r build
      - run: pnpm -r test
      - name: Run OTEL sample
        run: pnpm tsx scripts/otel-sample.ts
      - name: Upload OTEL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: otel-artifacts
          path: |
            evidence/otel-run.json
            evidence/otel-summary.json
