name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm db:generate
        env:
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1
      - run: pnpm db:validate
        env:
          PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: 1
      - run: pnpm -r build
      - run: pnpm -r test
