name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apgms
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: apgms/pnpm-lock.yaml
      - run: pnpm i
      - run: pnpm -r build
      - run: pnpm -r test

  docker-images:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - image: api-gateway
            dockerfile: ./apgms/services/api-gateway/Dockerfile
          - image: tax-engine
            dockerfile: ./apgms/services/tax-engine/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: ./apgms
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}
