name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable pnpm
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm test
      - name: Emit OTEL trace
        run: pnpm tsx scripts/otel-smoke.ts
        env:
          OTEL_ENABLED: "true"
      - name: Upload OTEL trace
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: otel-trace
          path: artifacts/otel/trace.json

  redteam:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm eval:redteam
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: redteam-report
          path: artifacts/eval/redteam-report.json

  golden:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm eval:golden
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: golden-report
          path: artifacts/eval/golden-report.json

  a11y:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Accessibility placeholder
        run: echo "No UI automation configured; manual report tracked in docs/accessibility/report.md"

  sca-sbom:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Generate SBOM
        run: pnpm sbom
      - name: Check allowlist
        run: pnpm tsx scripts/check-sbom.ts artifacts/sbom/sbom.json
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom
          path: artifacts/sbom/sbom.json

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API Gateway image
        run: docker build -f services/api-gateway/Dockerfile -t apgms/api-gateway:ci .
      - name: Inspect image
        run: docker image inspect apgms/api-gateway:ci
