name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm -r build
      - run: pnpm -r test

  compliance-pack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure artifacts directory
        run: |
          mkdir -p artifacts
          if [ -z "$(ls -A artifacts 2>/dev/null)" ]; then
            echo "No artifacts generated; inserting placeholder manifest." > artifacts/README.txt
          fi
      - name: Create compliance bundle
        run: |
          cd artifacts
          zip -r compliance.zip .
      - name: Upload compliance bundle
        uses: actions/upload-artifact@v4
        with:
          name: compliance-pack
          path: artifacts/compliance.zip
