name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm test
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push api-gateway image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/api-gateway/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}/api-gateway:${{ github.sha }}
            ${{ env.IMAGE_PREFIX }}/api-gateway:latest
          build-args: |
            GIT_SHA=${{ github.sha }}
      - name: Build and push tax-engine image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/tax-engine/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}/tax-engine:${{ github.sha }}
            ${{ env.IMAGE_PREFIX }}/tax-engine:latest
          build-args: |
            GIT_SHA=${{ github.sha }}
