name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm -r build
      - run: pnpm -r test
  otel-snapshot:
    name: OTEL snapshot
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm -r build
      - run: pnpm run otel:smoke
      - uses: actions/upload-artifact@v4
        with:
          name: otel-traces
          path: reports/otel-traces.ndjson
          if-no-files-found: error
