name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm -r build
      - run: pnpm -r test
      - name: Upload OTEL traces
        if: ${{ hashFiles('**/otel-traces.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: otel-traces
          path: '**/otel-traces.json'
          if-no-files-found: ignore
