name: CI

on: [push, pull_request]

defaults:
  run:
    working-directory: apgms

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: apgms/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm exec playwright install --with-deps
      - run: pnpm -r build
      - run: pnpm -r test

  axe:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: apgms/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm exec playwright install --with-deps
      - run: pnpm --filter @apgms/webapp test:axe

  lighthouse:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: apgms/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm --filter @apgms/webapp build
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: ./apgms/lighthouserc.json
          runs: 1
          uploadArtifacts: true
