name: Quality Gates

on:
  pull_request:
  workflow_dispatch:

jobs:
  golden-tests:
    name: Golden tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run golden quality gate
        run: pnpm golden

  redteam-checks:
    name: Red-team checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run red-team quality gate
        run: pnpm redteam
      - name: Upload red-team report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: redteam-report
          path: eval/redteam-report.json
          if-no-files-found: error
