name: Refresh OSF matrix

on:
  release:
    types:
      - published

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Install workspace dependencies
        run: pnpm install --frozen-lockfile
        working-directory: apgms
      - name: Refresh DSP OSF matrix
        run: pnpm run refresh:osf-matrix
        working-directory: apgms
      - name: Upload refreshed matrix
        uses: actions/upload-artifact@v4
        with:
          name: dsp-osf-matrix
          path: apgms/docs/dsp-osf/matrix.md
