name: Refresh DSP OSF matrix

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run refresh:osf-matrix
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh OSF control matrix"
          file_pattern: docs/dsp-osf/matrix.md
