name: Release
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (gateway)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-api-gateway
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
      - name: Build (gateway)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/api-gateway/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Trivy scan (gateway)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
        continue-on-error: true
      - name: Build & Push (gateway)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/api-gateway/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
