name: security
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  supply-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm
      - run: corepack enable && pnpm i --frozen-lockfile
      - name: SBOM (CycloneDX)
        run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json
      - name: Secret scan (gitleaks)
        uses: gitleaks/gitleaks-action@v2
      - name: SCA (npm audit)
        run: pnpm audit --audit-level=high
      - name: Docker scan (Trivy)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          format: table
          exit-code: '1'
          ignore-unfixed: true
