name: Webapp CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'apgms/webapp/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/webapp.yml'

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint webapp
        run: pnpm --filter @apgms/webapp lint

      - name: Typecheck webapp
        run: pnpm --filter @apgms/webapp typecheck

      - name: Run tests
        run: pnpm --filter @apgms/webapp test -- --run

      - name: Build webapp
        run: pnpm --filter @apgms/webapp build
