services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: apgms
      POSTGRES_PASSWORD: apgms
      POSTGRES_DB: apgms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apgms"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-gateway:
    build:
      context: ..
      dockerfile: services/api-gateway/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://apgms:apgms@postgres:5432/apgms
      PORT: "3000"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres-data:
